@startuml 活动图
title 管理员添加信息流程图

start

:登录系统;
:进入信息管理模块;

:输入要添加的信息;

if (信息完整吗?) then (是)
    :保存信息到系统;
    
    if (信息保存成功?) then (是)
        :显示添加信息成功信息;
    else (否)
        :显示添加信息失败原因;
    endif
else (否)
    :显示信息不完整提示;
endif

:查看已添加的信息;

stop
@enduml
