@startuml 活动图
title 教师添加成绩流程图

start

:查询学生信息;
:获取学生列表;

if (学生列表为空?) then (是)
    :显示无可添加成绩的学生信息;
    stop
else (否)
    :显示学生列表;
endif

:选择学生;

if (确认添加成绩?) then (是)
    :输入成绩信息;
    
    if (成绩信息有效?) then (是)
        :保存成绩到系统;
        :显示添加成绩成功信息;
    else (否)
        :显示成绩信息无效提示;
    endif
else (否)
    :返回学生列表;
endif

:查看已添加的成绩;

stop
@enduml
