@startuml 状态图
title 学生上课状态图

[*] --> 准备上课

准备上课 --> 上课中 : 进入教室
上课中 --> 上课中 : 听讲
上课中 --> 上课中 : 参与讨论
上课中 --> 下课中 : 上课结束

下课中 --> 完成 : 处理课后作业
完成 --> 准备上课 : 准备下次课程

上课中 --> 请假 : 请假
请假 --> 完成 : 返回课堂
请假 --> [*] : 旷课

@enduml
