@startuml 状态图
title 学生选课状态图

[*] --> 查询课程

查询课程 --> 选择课程 : 查询成功
选择课程 --> 确认选课 : 选择课程

确认选课 --> 选课成功 : 确认无误
确认选课 --> 选课失败 : 确认有误

选课成功 --> 查看已选课程 : 添加成绩
选课失败 --> 查询课程 : 返回选择课程

查看已选课程 --> [*] : 完成选课
@enduml
